#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Wed May  8 12:23:49 2024
#

from externo import CartaBase, Mazo, Estrategia
import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


# region Card
class Card(CartaBase):
    def __init__(self, ind: int) -> None:
        super().__init__(ind)
        self.ind = ind
        self.img = wx.Bitmap()
        self.img.LoadFile(f"./imgs/cards/m{ind:02d}.png")

    def getCardBitmap(self):
        return self.img
# endregion

class Hand():
    def __init__(self, sizer, staticText, cards: list[Card] = None, bet = 0) -> None:
        self.sizer = sizer
        self.staticText = staticText
        self.bet = bet
        self.cards = [] if not cards else cards

    def giveCard(self, deck, amount, gamePanel):
        for _ in range(amount):
            cardToAdd = deck.reparte()
            self.cards.append(cardToAdd)
            cardBitmap = self.cards[-1].getCardBitmap()
            staticBitMap = wx.StaticBitmap(gamePanel, wx.ID_ANY, cardBitmap)

            self.sizer.Add(staticBitMap, 0, 0, 0)
        #print(self.sizer.GetChildren())
        self.staticText.SetLabel(f"CROUPIER\n(20)\nActiva")

    def getHandValue(self):
        pass


class Player():
    def __init__(self, hands: list[Hand] = None, isCroupier = False):
        self.hands = [] if not hands else hands
        self.isCroupier = isCroupier

    def addHand(self, hand):
        self.hands.append(hand)

class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):

        self.player = Player()
        self.croupier = Player(isCroupier = True)
        self.deck = Mazo(Card, None)

        # begin wxGlade: mainWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.FULL_REPAINT_ON_RESIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("Blackjack")
        self.SetBackgroundColour(wx.Colour(255, 255, 255))

        self.statusBar = self.CreateStatusBar(2)
        self.statusBar.SetStatusWidths([-1, 0])
        # statusbar fields
        statusBar_fields = ["Selecciona jugada", ""]
        for i in range(len(statusBar_fields)):
            self.statusBar.SetStatusText(statusBar_fields[i], i)

        gameSizer = wx.BoxSizer(wx.HORIZONTAL)

        gameOptionsSizer = wx.BoxSizer(wx.VERTICAL)
        gameSizer.Add(gameOptionsSizer, 10, wx.EXPAND, 0)

        gameModeSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Modo de juego"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameModeSizer, 7, wx.ALL | wx.EXPAND, 9)

        self.manualButton = wx.RadioButton(self, wx.ID_ANY, "Manual")
        self.manualButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameModeSizer.Add(self.manualButton, 60, wx.ALIGN_CENTER_VERTICAL, 0)

        self.automaticButton = wx.RadioButton(self, wx.ID_ANY, u"Automático")
        self.automaticButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameModeSizer.Add(self.automaticButton, 40, wx.ALIGN_CENTER_VERTICAL, 0)

        gameDelaySizer = wx.BoxSizer(wx.HORIZONTAL)
        gameOptionsSizer.Add(gameDelaySizer, 6, wx.ALL | wx.EXPAND, 9)

        delayText = wx.StaticText(self, wx.ID_ANY, "Retardo:")
        delayText.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameDelaySizer.Add(delayText, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 8)

        self.delayInput = wx.TextCtrl(self, wx.ID_ANY, "25", style=wx.TE_CENTRE)
        self.delayInput.SetMinSize((65, 23))
        gameDelaySizer.Add(self.delayInput, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 10)

        msText = wx.StaticText(self, wx.ID_ANY, "ms.")
        msText.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameDelaySizer.Add(msText, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        gameActionSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Acción"), wx.VERTICAL)
        gameOptionsSizer.Add(gameActionSizer, 17, wx.ALL | wx.EXPAND, 9)

        self.askButton = wx.Button(self, wx.ID_ANY, "PEDIR")
        self.askButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        gameActionSizer.Add(self.askButton, 25, wx.ALL | wx.EXPAND, 2)

        self.doubleButton = wx.Button(self, wx.ID_ANY, "DOBLAR")
        self.doubleButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        gameActionSizer.Add(self.doubleButton, 25, wx.ALL | wx.EXPAND, 2)

        self.closeButton = wx.Button(self, wx.ID_ANY, "CERRAR")
        self.closeButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        gameActionSizer.Add(self.closeButton, 25, wx.ALL | wx.EXPAND, 2)

        self.splitButton = wx.Button(self, wx.ID_ANY, "SEPARAR")
        self.splitButton.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        gameActionSizer.Add(self.splitButton, 25, wx.ALL | wx.EXPAND, 2)

        self.separatorPanel = wx.Panel(self, wx.ID_ANY)
        gameOptionsSizer.Add(self.separatorPanel, 15, wx.EXPAND, 0)

        gameCounterSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Partida"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameCounterSizer, 7, wx.ALL | wx.EXPAND, 9)

        gameCounterText = wx.StaticText(self, wx.ID_ANY, "1", style=wx.ALIGN_CENTER_HORIZONTAL)
        gameCounterText.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameCounterSizer.Add(gameCounterText, 100, wx.ALIGN_CENTER_VERTICAL, 0)

        gameGlobalBalanceSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Balance global"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameGlobalBalanceSizer, 7, wx.ALL | wx.EXPAND, 9)

        globalBalanceText = wx.StaticText(self, wx.ID_ANY, u"+15 €", style=wx.ALIGN_CENTER_HORIZONTAL)
        globalBalanceText.SetForegroundColour(wx.Colour(48, 194, 48))
        globalBalanceText.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameGlobalBalanceSizer.Add(globalBalanceText, 100, wx.ALIGN_CENTER_VERTICAL, 0)

        gameBalanceSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Balance partida actual"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameBalanceSizer, 7, wx.ALL | wx.EXPAND, 9)

        gameBalaneText = wx.StaticText(self, wx.ID_ANY, u"+0 €", style=wx.ALIGN_CENTER_HORIZONTAL)
        gameBalaneText.SetForegroundColour(wx.Colour(48, 194, 48))
        gameBalaneText.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameBalanceSizer.Add(gameBalaneText, 100, wx.ALIGN_CENTER_VERTICAL, 0)

        gameCountdownSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Cuenta atrás"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameCountdownSizer, 7, wx.ALL | wx.EXPAND, 9)

        countDownText = wx.StaticText(self, wx.ID_ANY, "2", style=wx.ALIGN_CENTER_HORIZONTAL)
        countDownText.SetFont(wx.Font(25, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameCountdownSizer.Add(countDownText, 100, wx.ALIGN_CENTER_VERTICAL, 0)

        self.gamePanel = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.gamePanel.SetBackgroundColour(wx.Colour(237, 237, 237))
        self.gamePanel.SetScrollRate(10, 10)
        gameSizer.Add(self.gamePanel, 90, wx.EXPAND, 0)

        self.gamePanelSizer = wx.BoxSizer(wx.VERTICAL)

        # croupierHandSizer = wx.BoxSizer(wx.HORIZONTAL)
        # self.gamePanelSizer.Add(croupierHandSizer, 0, wx.EXPAND, 0)

        # croupierHandText = wx.StaticText(self.gamePanel, wx.ID_ANY, "CROUPIER\n(8)\nActiva", style=wx.ALIGN_CENTER_HORIZONTAL)
        # croupierHandText.SetMinSize((145, 200))
        # croupierHandText.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        # croupierHandSizer.Add(croupierHandText, 0, wx.ALL, 10)

        # self.croupier.addHand(Hand(croupierHandSizer, croupierHandText))

        # playerHandSizer = wx.BoxSizer(wx.HORIZONTAL)
        # self.gamePanelSizer.Add(playerHandSizer, 10, wx.EXPAND, 0)
        
        # playerHandText = wx.StaticText(self.gamePanel, wx.ID_ANY, u"(20)\n50€\nActiva", style=wx.ALIGN_CENTER_HORIZONTAL)
        # playerHandText.SetMinSize((145, 200))
        # playerHandText.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))

        # playerHandSizer.Add(playerHandText, 0, wx.ALL, 10)

        self.gamePanel.SetSizer(self.gamePanelSizer)

        self.SetSizer(gameSizer)
        gameSizer.Fit(self)
        gameSizer.SetSizeHints(self)

        self.Layout()
        self.Centre()

        self.Bind(wx.EVT_RADIOBUTTON, self.handleClickManualButton, self.manualButton)
        self.Bind(wx.EVT_RADIOBUTTON, self.handleClickAutomaticButton, self.automaticButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickAskButton, self.askButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickDoubleButton, self.doubleButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickCloseButton, self.closeButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickSplitButton, self.splitButton)
        # end wxGlade

        self.chooseBet = ChooseBet(None, wx.ID_ANY, "")
        self.blackJackPopUp = BlackJackPopUp(None, wx.ID_ANY, "")


    def handleClickManualButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickManualButton' not implemented!")
        event.Skip()

    def handleClickAutomaticButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickAutomaticButton' not implemented!")
        event.Skip()

    def handleClickAskButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickAskButton' not implemented!")
        event.Skip()

    def handleClickDoubleButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickDoubleButton' not implemented!")
        event.Skip()

    def handleClickCloseButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickCloseButton' not implemented!")
        event.Skip()

    def handleClickSplitButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickSplitButton' not implemented!")
        event.Skip()

    def addHandToGamePanel(self, player, label, bet = 0):
        newSizer = wx.BoxSizer(wx.HORIZONTAL)
        self.gamePanelSizer.Add(newSizer, 0, wx.EXPAND, 0)

        newSizerText = wx.StaticText(self.gamePanel, wx.ID_ANY, label, style=wx.ALIGN_CENTER_HORIZONTAL)
        newSizerText.SetMinSize((145, 200))
        newSizerText.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        newSizer.Add(newSizerText, 0, wx.ALL, 10)

        player.addHand(Hand(newSizer, newSizerText, bet))

# end of class mainWindow

class ChooseBet(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ChooseBet.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((220, 250))
        self.SetTitle("Nueva partida")
        self.selectedBet = 2

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        chooseBetSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Elija su apuesta"), wx.VERTICAL)
        sizer_1.Add(chooseBetSizer, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.TOP, 17)

        self.lowBet = wx.RadioButton(self, 2, u"2€ ")
        self.lowBet.SetValue(1)
        chooseBetSizer.Add(self.lowBet, 33, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.mediumBet = wx.RadioButton(self, 10, u"10€")
        chooseBetSizer.Add(self.mediumBet, 33, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.highBet = wx.RadioButton(self, 50, u"50€")
        chooseBetSizer.Add(self.highBet, 33, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"¿Quiere seguir jugando?")
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 2)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 10)

        self.acceptBet = wx.Button(self, wx.ID_YES, "")
        sizer_2.AddButton(self.acceptBet)

        self.denyBet = wx.Button(self, wx.ID_NO, "")
        sizer_2.AddButton(self.denyBet)

        sizer_2.Realize()

        self.SetSizer(sizer_1)

        self.Layout()
        self.Centre()

        self.Bind(wx.EVT_RADIOBUTTON, self.setSelectedBet, self.lowBet)
        self.Bind(wx.EVT_RADIOBUTTON, self.setSelectedBet, self.mediumBet)
        self.Bind(wx.EVT_RADIOBUTTON, self.setSelectedBet, self.highBet)
        self.Bind(wx.EVT_BUTTON, self.handleExitScreenBet, self.acceptBet)
        self.Bind(wx.EVT_BUTTON, self.handleExitScreenBet, self.denyBet)
        # end wxGlade


    def setSelectedBet(self, event):
        self.selectedBet = event.GetId()

    def handleExitScreenBet(self, event):  # wxGlade: ChooseBet.<event_handler>
       self.EndModal(event.GetId())



# end of class ChooseBet

class BlackJackPopUp(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BlackJackPopUp.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((550, 400))
        self.SetTitle("dialog")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("./imgs/blackjack.jpeg", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(bitmap_1, 1, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALL, 8)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"¡Enhorabuena, has ganado 15€!", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_2.Add(label_1, 90, wx.ALIGN_CENTER_VERTICAL, 0)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        sizer_2.Realize()

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_OK.GetId())

        self.Layout()
        self.Centre()
        # end wxGlade

# end of class BlackJackPopUp

class Game(wx.App):
    def OnInit(self):

        self.mainWindow = MainWindow(None, wx.ID_ANY, "")
        self.chooseBetWindow = ChooseBet(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mainWindow)
        self.mainWindow.Show()
        self.mainWindow.CenterOnScreen()

        buttonId = self.chooseBetWindow.ShowModal()
        
        if buttonId != wx.ID_YES:
            self.mainWindow.Close()
           
        self.mainWindow.addHandToGamePanel(self.mainWindow.croupier, "")
        self.mainWindow.croupier.hands[0].giveCard(self.mainWindow.deck, 2, self.mainWindow.gamePanel)
        self.mainWindow.gamePanel.Layout()

        return True

# end of class Game

if __name__ == "__main__":

    GUIJack = Game(0)
    GUIJack.MainLoop()
