#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Mon May  6 22:25:44 2024
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class mainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: mainWindow.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("Blackjack")

        self.statusBar = self.CreateStatusBar(2)
        self.statusBar.SetStatusWidths([-1, 0])
        # statusbar fields
        statusBar_fields = ["Selecciona jugada", ""]
        for i in range(len(statusBar_fields)):
            self.statusBar.SetStatusText(statusBar_fields[i], i)

        gameSizer = wx.BoxSizer(wx.HORIZONTAL)

        gameOptionsSizer = wx.BoxSizer(wx.VERTICAL)
        gameSizer.Add(gameOptionsSizer, 0, wx.EXPAND | wx.SHAPED, 0)

        gameModeSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Modo de juego"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameModeSizer, 0, wx.EXPAND, 0)

        self.manualButton = wx.RadioButton(self, wx.ID_ANY, "Manual")
        gameModeSizer.Add(self.manualButton, 0, 0, 0)

        self.automaticButton = wx.RadioButton(self, wx.ID_ANY, u"Automático")
        gameModeSizer.Add(self.automaticButton, 0, 0, 0)

        gameDelaySizer = wx.BoxSizer(wx.HORIZONTAL)
        gameOptionsSizer.Add(gameDelaySizer, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "Retardo:")
        label_1.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        gameDelaySizer.Add(label_1, 0, 0, 0)

        self.delayInput = wx.TextCtrl(self, wx.ID_ANY, "0.25")
        gameDelaySizer.Add(self.delayInput, 0, 0, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, "ms.")
        gameDelaySizer.Add(label_2, 0, 0, 0)

        gameActionSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Acción"), wx.VERTICAL)
        gameOptionsSizer.Add(gameActionSizer, 0, wx.EXPAND, 0)

        self.askButton = wx.Button(self, wx.ID_ANY, "Pedir")
        gameActionSizer.Add(self.askButton, 0, wx.EXPAND, 0)

        self.doubleButton = wx.Button(self, wx.ID_ANY, "Doblar")
        gameActionSizer.Add(self.doubleButton, 0, wx.EXPAND, 0)

        self.closeButton = wx.Button(self, wx.ID_ANY, "Cerrar")
        gameActionSizer.Add(self.closeButton, 0, wx.EXPAND, 0)

        self.splitButton = wx.Button(self, wx.ID_ANY, "Separar")
        gameActionSizer.Add(self.splitButton, 0, wx.EXPAND, 0)

        gameCounterSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Partida"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameCounterSizer, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, "1", style=wx.ALIGN_CENTER_HORIZONTAL)
        gameCounterSizer.Add(label_3, 0, wx.EXPAND, 0)

        gameGlobalBalanceSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Balance global"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameGlobalBalanceSizer, 0, wx.EXPAND, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, "")
        gameGlobalBalanceSizer.Add(label_4, 0, 0, 0)

        gameBalanceSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Balance partida actual"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameBalanceSizer, 0, wx.EXPAND, 0)

        label_5 = wx.StaticText(self, wx.ID_ANY, "")
        gameBalanceSizer.Add(label_5, 0, 0, 0)

        gameCountdownSizer = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, u"Cuenta atrás"), wx.HORIZONTAL)
        gameOptionsSizer.Add(gameCountdownSizer, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, "30")
        gameCountdownSizer.Add(label_6, 0, 0, 0)

        self.gamePanel = wx.Panel(self, wx.ID_ANY)
        gameSizer.Add(self.gamePanel, 0, 0, 0)

        self.SetSizer(gameSizer)
        gameSizer.Fit(self)
        gameSizer.SetSizeHints(self)

        self.Layout()

        self.Bind(wx.EVT_RADIOBUTTON, self.handleClickManualButton, self.manualButton)
        self.Bind(wx.EVT_RADIOBUTTON, self.handleClickAutomaticButton, self.automaticButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickAskButton, self.askButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickDoubleButton, self.doubleButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickCloseButton, self.closeButton)
        self.Bind(wx.EVT_BUTTON, self.handleClickSplitButton, self.splitButton)
        # end wxGlade

    def handleClickManualButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickManualButton' not implemented!")
        event.Skip()

    def handleClickAutomaticButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickAutomaticButton' not implemented!")
        event.Skip()

    def handleClickAskButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickAskButton' not implemented!")
        event.Skip()

    def handleClickDoubleButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickDoubleButton' not implemented!")
        event.Skip()

    def handleClickCloseButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickCloseButton' not implemented!")
        event.Skip()

    def handleClickSplitButton(self, event):  # wxGlade: mainWindow.<event_handler>
        print("Event handler 'handleClickSplitButton' not implemented!")
        event.Skip()

# end of class mainWindow

class MyApp(wx.App):
    def OnInit(self):
        self.mainWindow = mainWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mainWindow)
        self.mainWindow.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
